applications:     

# Basic      


## AI

  openshift-ai-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/openshift-ai-operator

  kueue-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/kueue-operator

## Data Science Cluster
  datasciencecluster-instance:
    annotations:
      argocd.argoproj.io/sync-wave: '10'
    source:
      path: components/datasciencecluster-instance
