      
projects: {}

applications: 

# Basics

  openshift-config:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-config      
    source:
      path: clusters/local/overlays/openshift-config